(() => {
  const KEY='swedsnus-v2-subscriptions';
  const intervals={1:'Varje vecka',2:'Varannan vecka',4:'Var 4:e vecka',8:'Var 8:e vecka'};
  const seed=[{id:'SUB-2048',status:'active',intervalWeeks:4,nextDelivery:'2026-09-14',changeDeadline:'2026-09-12',address:'Hemsjövägen 12, 441 96 Alingsås',payment:'Avarda · •••• 4821',items:[{id:'original-white-portion__compact-20-dosor',packQty:2,qty:1}]}];
  const read=()=>{try{const value=JSON.parse(localStorage.getItem(KEY)||'null');return Array.isArray(value)?value:seed;}catch{return seed;}};
  const write=value=>{localStorage.setItem(KEY,JSON.stringify(value));render();};
  const escape=value=>window.SwedsnusV2?.escapeHtml(value)||String(value);
  const date=value=>new Intl.DateTimeFormat('sv-SE',{day:'numeric',month:'long',year:'numeric'}).format(new Date(`${value}T12:00:00`));
  const details=item=>{const row=window.SwedsnusV2?.find(item.id);const pack=row?window.SwedsnusV2.packs(row).find(entry=>entry.packQty===item.packQty):null;return {name:row?window.SwedsnusV2.name(row):'Produkt',total:Number(pack?.total||0)};};
  const total=subscription=>subscription.items.reduce((sum,item)=>sum+details(item).total*(item.qty||1),0);
  const money=value=>window.SwedsnusV2?.money(value)||`${Number(value).toLocaleString('sv-SE')} kr`;

  function selection(scope){const choice=scope?.querySelector('[data-purchase-choice]');const mode=choice?.querySelector('input:checked')?.value||'once';return {purchaseMode:mode,intervalWeeks:mode==='subscription'?Number(choice.querySelector('select')?.value||4):null};}
  function updateChoice(choice){const subscribed=choice.querySelector('input:checked')?.value==='subscription';choice.classList.toggle('subscribed',subscribed);choice.querySelector('[data-subscription-interval]').hidden=!subscribed;choice.querySelector('[data-subscription-copy]').hidden=!subscribed;}
  function ensureModal(){if(document.querySelector('[data-subscription-modal]'))return;const modal=document.createElement('div');modal.className='subscription-modal';modal.dataset.subscriptionModal='';modal.hidden=true;modal.innerHTML=`<div class="subscription-modal-backdrop" data-subscription-close></div><section class="subscription-modal-card" role="dialog" aria-modal="true" aria-labelledby="subscription-modal-title"><button class="subscription-modal-close" type="button" data-subscription-close aria-label="Stäng">×</button><p class="kicker">Återkommande leverans</p><h2 id="subscription-modal-title" data-subscription-modal-name>Prenumerera</h2><p class="subscription-modal-intro">Välj mängd och hur ofta produkten ska levereras.</p><form data-subscription-modal-form><label>Förpackningsstorlek<select name="packQty" data-subscription-pack></select></label><label>Leveransintervall<select name="intervalWeeks"><option value="1">Varje vecka</option><option value="2">Varannan vecka</option><option value="4" selected>Var 4:e vecka</option><option value="8">Var 8:e vecka</option></select></label><div class="subscription-modal-summary"><span>Pris för första leveransen</span><strong data-subscription-modal-price>0 kr</strong></div><button class="btn primary" type="submit">Prenumerera</button><p>Första köpet slutförs hos Avarda där du godkänner återkommande betalning. Du kan sedan pausa eller avsluta under Mina sidor.</p></form></section>`;document.body.append(modal);}
  function openModal(id){ensureModal();const row=window.SwedsnusV2?.find(id);if(!row)return;const modal=document.querySelector('[data-subscription-modal]');modal.dataset.productId=window.SwedsnusV2.key(row);modal.querySelector('[data-subscription-modal-name]').textContent=window.SwedsnusV2.name(row);modal.querySelector('[data-subscription-pack]').innerHTML=window.SwedsnusV2.packs(row).map(pack=>`<option value="${pack.packQty}" data-total="${pack.total}" data-per-dose="${pack.perDose}">${pack.label}${row.amount_dosor?` · ${pack.units} dosor`:''} · ${money(pack.total)}</option>`).join('');modal.querySelector('[data-subscription-modal-price]').textContent=money(window.SwedsnusV2.packs(row)[0].total);modal.hidden=false;document.body.classList.add('modal-open');modal.querySelector('select')?.focus();}
  function closeModal(){const modal=document.querySelector('[data-subscription-modal]');if(modal)modal.hidden=true;document.body.classList.remove('modal-open');}
  function addFromModal(form){const modal=form.closest('[data-subscription-modal]');const row=window.SwedsnusV2?.find(modal.dataset.productId);const option=form.elements.packQty.selectedOptions[0];if(!row||!option||!window.SwedsnusCart)return;const packQty=Number(option.value);const intervalWeeks=Number(form.elements.intervalWeeks.value);window.SwedsnusCart.addItems([{cartKey:`${window.SwedsnusV2.key(row)}::${packQty}::subscription::${intervalWeeks}`,id:window.SwedsnusV2.key(row),name:window.SwedsnusV2.name(row),packQty,totalPrice:Number(option.dataset.total),perDose:Number(option.dataset.perDose),qty:1,purchaseMode:'subscription',intervalWeeks}]);closeModal();document.querySelector('[data-cart-drawer]')?.classList.add('open');}
  function line(subscription,item,index){const product=details(item);return `<div class="subscription-line"><div><strong>${escape(product.name)}</strong><span>${item.packQty}-pack · ${item.packQty*(item.qty||1)} förpackningar</span></div><label>Antal<input type="number" min="1" max="10" value="${item.qty||1}" data-subscription-quantity="${escape(subscription.id)}" data-item-index="${index}" ${subscription.status==='active'?'':'disabled'}></label><strong>${money(product.total*(item.qty||1))}</strong></div>`;}
  function card(subscription){const active=subscription.status==='active';return `<article class="subscription-card"><div class="subscription-card-head"><div><span class="account-label">Prenumeration ${escape(subscription.id)}</span><h2>${active?'Aktiv':'Pausad'}</h2></div><span class="status-badge${active?' active':''}">${active?'Nästa order '+date(subscription.nextDelivery):'Inga ordrar planerade'}</span></div><div class="subscription-next"><div><span>Nästa order</span><strong>${date(subscription.nextDelivery)}</strong></div><div><span>Ändra senast</span><strong>${date(subscription.changeDeadline)}</strong></div><div><span>Beräknat varuvärde</span><strong>${money(total(subscription))}</strong></div><div><span>Betalning</span><strong>${escape(subscription.payment)}</strong></div><div><span>Leveransadress</span><strong>${escape(subscription.address)}</strong></div></div><div class="subscription-lines">${subscription.items.map((item,index)=>line(subscription,item,index)).join('')}</div><div class="subscription-settings"><label>Leveransintervall<select data-subscription-frequency="${escape(subscription.id)}" ${active?'':'disabled'}>${Object.entries(intervals).map(([value,label])=>`<option value="${value}"${Number(value)===subscription.intervalWeeks?' selected':''}>${label}</option>`).join('')}</select></label><div class="subscription-actions"><button class="btn" type="button" data-subscription-skip="${escape(subscription.id)}" ${active?'':'disabled'}>Hoppa över nästa</button><button class="btn" type="button" data-subscription-toggle="${escape(subscription.id)}">${active?'Pausa':'Återuppta'}</button><button class="subscription-cancel" type="button" data-subscription-cancel="${escape(subscription.id)}">Avsluta</button></div></div><p class="subscription-reminder">Inför nästa order skickas en avisering med aktuellt innehåll, pris och sista tid för ändring. Slutpriset fastställs när ordern skapas.</p></article>`;}
  function render(){const root=document.querySelector('[data-subscriptions-root]');if(!root||!window.SwedsnusV2?.state.ready)return;if(window.SwedsnusAccount&&!window.SwedsnusAccount.loggedIn()){root.innerHTML=`<div class="account-login"><p class="kicker">Mina sidor</p><h1>Logga in</h1><p>Logga in för att se och hantera dina prenumerationer.</p><button class="btn primary" type="button" data-demo-login>Logga in</button></div>`;return;}const list=read();root.innerHTML=`${window.SwedsnusAccount?.nav?.('subscriptions')||''}<header class="account-hero compact"><div><p class="kicker">Återkommande leveranser</p><h1>Prenumerationer</h1><p>Ändra mängd och intervall, hoppa över en order, pausa eller avsluta.</p></div><a class="btn" href="subscribe.html">Lägg till produkter</a></header><section class="subscription-notice"><strong>Så fungerar nästa order</strong><p>Du aviseras före varje order med aktuellt innehåll och pris. Pris, lager, leveransadress och ålderskontroll valideras innan ordern skapas.</p></section><div class="subscription-list">${list.length?list.map(card).join(''):'<div class="account-panel"><h2>Inga prenumerationer</h2><p>Välj en prenumererbar produkt för att komma igång.</p><a class="btn primary" href="subscribe.html">Se produkter</a></div>'}</div><p class="form-feedback" data-subscription-feedback role="status"></p>`;}
  function update(id,callback,message){const list=read();const entry=list.find(item=>item.id===id);if(!entry)return;callback(entry);write(list);requestAnimationFrame(()=>{const el=document.querySelector('[data-subscription-feedback]');if(el)el.textContent=message;});}
  window.SwedsnusSubscriptions={read,write,selection,intervalLabel:value=>intervals[value]||`Var ${value}:e vecka`,render};
  document.addEventListener('change',event=>{const radio=event.target.closest('[data-purchase-choice] input[type="radio"]');if(radio)updateChoice(radio.closest('[data-purchase-choice]'));const pack=event.target.closest('[data-subscription-pack]');if(pack)pack.closest('[data-subscription-modal]').querySelector('[data-subscription-modal-price]').textContent=money(Number(pack.selectedOptions[0].dataset.total));const frequency=event.target.closest('[data-subscription-frequency]');if(frequency)update(frequency.dataset.subscriptionFrequency,item=>item.intervalWeeks=Number(frequency.value),'Leveransintervallet har sparats.');const quantity=event.target.closest('[data-subscription-quantity]');if(quantity)update(quantity.dataset.subscriptionQuantity,item=>item.items[Number(quantity.dataset.itemIndex)].qty=Math.max(1,Number(quantity.value)||1),'Mängden har sparats.');});
  document.addEventListener('submit',event=>{if(event.target.matches('[data-subscription-modal-form]')){event.preventDefault();addFromModal(event.target);}});
  document.addEventListener('click',event=>{const open=event.target.closest('[data-subscription-open]');if(open){event.preventDefault();openModal(open.dataset.subscriptionOpen);return;}if(event.target.closest('[data-subscription-close]'))closeModal();const toggle=event.target.closest('[data-subscription-toggle]');if(toggle)update(toggle.dataset.subscriptionToggle,item=>item.status=item.status==='active'?'paused':'active',toggle.textContent==='Pausa'?'Prenumerationen är pausad.':'Prenumerationen är aktiv igen.');const skip=event.target.closest('[data-subscription-skip]');if(skip)update(skip.dataset.subscriptionSkip,item=>{const next=new Date(`${item.nextDelivery}T12:00:00`);next.setDate(next.getDate()+item.intervalWeeks*7);item.nextDelivery=next.toISOString().slice(0,10);const deadline=new Date(next);deadline.setDate(deadline.getDate()-2);item.changeDeadline=deadline.toISOString().slice(0,10);},'Nästa order har flyttats fram.');const cancel=event.target.closest('[data-subscription-cancel]');if(cancel&&confirm('Vill du avsluta prenumerationen?'))write(read().filter(item=>item.id!==cancel.dataset.subscriptionCancel));});
  document.addEventListener('keydown',event=>{if(event.key==='Escape')closeModal();});
  document.addEventListener('swedsnus-v2:products-ready',render);
})();
